package Ventanas;

import Paquete.Controlador;
import Paquete.Mimodelo;
import javax.swing.JOptionPane;

public class PROFESSIONES extends javax.swing.JInternalFrame {

    Controlador control = new Controlador();
    Mimodelo modelo = new Mimodelo();
    String idProfesion = "";

    public PROFESSIONES() {
        initComponents();

        tbProfesiones.setModel(modelo);
        modelo.setColumnIdentifiers(new String[]{"id", "Profesión"});
        control.objControles.setWidthTableColumn(tbProfesiones, 300, 1);
        MostrarProfesiones();
    }

    public void Crear() {
        if (idProfesion.length() > 0) {
            JOptionPane.showMessageDialog(null, "Estamos en modo Edicion");
            txProfesion.grabFocus();
            return;
        }
        if (txProfesion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, " Tienes que ingresar la Profesion");
            txProfesion.grabFocus();
        } else {
            control.Sql = "select* from profesion where  nomprofe='" + txProfesion.getText() + "'";
            if (control.Verificarconsulta(control.Sql)) {
                JOptionPane.showMessageDialog(null, "La profesion " + txProfesion.getText()
                        + "' \n Ya existe");
                control.objControles.MarcarTexto(txProfesion);
            } else {
                control.CrearRegistro("insert into profesion values('" + txProfesion.getText() + "')");
                Cancelar();
            }
        }
    }

    public void Editar() {
        if (txProfesion.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "No hay profesion Seleccionada");
            txProfesion.grabFocus();
        } else {
            control.Sql = "select* from profesion where  nomprofe='" + txProfesion.getText()
                    + "and idprofesion <>'" + idProfesion + "'";
            if (control.Verificarconsulta(control.Sql)) {
                JOptionPane.showMessageDialog(null, "La profesion " + txProfesion.getText()
                        + "' \n No se debe repetir");
                control.objControles.MarcarTexto(txProfesion);
            } else {
                control.Sql = "update profesion set nomprofe='" + txProfesion.getText() + "' where idprofesion = '"
                        + idProfesion + "'";
                control.EditarRegistro(control.Sql);
                Cancelar();
            }
        }
    }

    public void Eliminar() {
        if (tbProfesiones.getSelectedRow() > -1) {
            if (JOptionPane.showConfirmDialog(null, "Estas seguro de Eliminar \n "
                    + "La profesion: " + tbProfesiones.getValueAt(tbProfesiones.getSelectedRow(), 1).toString(), "Confirmar", 0) == 0) {
                control.Sql = "select* from profesionemple where  idprofesion='" + idProfesion + "'";
                if (control.Verificarconsulta(control.Sql)) {
                    JOptionPane.showMessageDialog(null, "La profesion " + tbProfesiones.getValueAt(tbProfesiones.getSelectedRow(), 1).toString()
                            + "' \n No se puede Eliminar");

                } else {
                    control.Sql = "delete  from profesion where  idprofesion ='" + idProfesion + "'";
                    JOptionPane.showMessageDialog(null, control.EliminarRegistro(control.Sql));

                }
                Cancelar();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar lo que quieres Eliminar");
        }
    }

    public void Cancelar() {
        tbProfesiones.clearSelection();
        txBuscar.setText("");
        txProfesion.setText("");
        idProfesion = "";
        MostrarProfesiones();
    }

    public void MostrarProfesiones() {
        control.Sql = "select * from profesion where  nomprofe like '%" + txBuscar.getText() + "%'";
        control.LlenarJTabla(modelo, control.Sql, 2);
    }
     public void Seleccionar(){
     if(tbProfesiones.getSelectedRow()>-1){
      idProfesion=tbProfesiones.getValueAt(tbProfesiones.getSelectedRow(), 0).toString();
      txProfesion.setText(tbProfesiones.getValueAt(tbProfesiones.getSelectedRow(), 1).toString());
     }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txProfesion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        bSalir = new javax.swing.JButton();
        bCrear = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProfesiones = new javax.swing.JTable();
        txBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la profesion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Profesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel2.add(txProfesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 25, 520, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSalir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        bSalir.setMnemonic('s');
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel3.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 110, 45));

        bCrear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add-icon.png"))); // NOI18N
        bCrear.setMnemonic('c');
        bCrear.setText("Crear");
        bCrear.setMargin(new java.awt.Insets(2, 1, 2, 14));
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });
        jPanel3.add(bCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 45));

        bEditar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Edit.png"))); // NOI18N
        bEditar.setMnemonic('d');
        bEditar.setText("Editar");
        bEditar.setMargin(new java.awt.Insets(2, 1, 2, 14));
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });
        jPanel3.add(bEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 45));

        bEliminar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        bEliminar.setMnemonic('e');
        bEliminar.setText("Eliminar");
        bEliminar.setMargin(new java.awt.Insets(2, 1, 2, 14));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 115, 45));

        bCancelar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        bCancelar.setMnemonic('a');
        bCancelar.setText("Cancelar");
        bCancelar.setMargin(new java.awt.Insets(2, 1, 2, 14));
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(bCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 115, 45));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Profesiones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(51, 0, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbProfesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProfesiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProfesionesMouseClicked(evt);
            }
        });
        tbProfesiones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbProfesionesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbProfesiones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 610, 210));

        txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 25, 560, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Buscar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
        //     control.LlenarCombo(FrmProfesionesdelEmpleado.cboProfesion, "select * from profesion", 2);
        //     FrmProfesionesdelEmpleado ver=new FrmProfesionesdelEmpleado();
        //     control.mostrar(ElMenu.jDesktopPane2,ver );
    }//GEN-LAST:event_bSalirActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
Crear();
    }//GEN-LAST:event_bCrearActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
Editar();
    }//GEN-LAST:event_bEditarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
Eliminar();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
Cancelar();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tbProfesionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProfesionesMouseClicked
Seleccionar();
    }//GEN-LAST:event_tbProfesionesMouseClicked

    private void tbProfesionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbProfesionesKeyReleased

    }//GEN-LAST:event_tbProfesionesKeyReleased

    private void txBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txBuscarKeyReleased

    }//GEN-LAST:event_txBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProfesiones;
    private javax.swing.JTextField txBuscar;
    private javax.swing.JTextField txProfesion;
    // End of variables declaration//GEN-END:variables
}
